### ISSUE TITLE
Open Chat: Positioning not exact

### ISSUE THREAD

**Issue by Wunderfitz** [Wunderfitz/harbour-fernschreiber#1]
When opening a new chat, the list is not always correctly positioned at the last read message. Seems to be related to the list view items' height that is dynamic and depends if there is a picture/video/sticker etc.. There is another option, but that is much slower and delays the opening of the chat... Let's see how it can be corrected. ;)

**Comment by jgibbon** [comment]
As I see it, there are two very much interconnected, but possibly separate issues here:
1. List delegates having different heights, so the ListView can not correctly guess the scroll amount necessary for uninitialized delegates.
I don't know if this is the "much slower" option you've had in mind (it's slower than doing nothing, but … everything is), but for delegates that do not change height themselves (see 2.), we could implement a custom scrollToIndex function that does more or less the following:
   - setting `highlightFollowsCurrentItem` to `true` on the ListView (`highlightMoveDuration`, `highlightResizeDuration` can be 0; `highlightRangeMode` can be `ListView.StrictlyEnforceRange` if `highlightFollowsCurrentItem===true`, otherwise `ListView.NoHighlightRange` – also there'd have to be an invisible highlight element)
   - setting `currentIndex`
   - starting a (very short) Timer to reset `highlightFollowsCurrentItem` to false
2. List delegates changing their height after initialization. This obviously happens through content loaded/changed afterwards, which pushes following delegates down (or possibly pulls up).
This one is interesting, as well, and I don't think* it can be really solved without either doing everything synchronously (well, no.) or manually reacting to height changes for items that are above the bottom of the viewport. Here's something I thought of that is neither tested nor fully thought through – consider it a start of a brainstorming.
   - a delegate would need to remember its "initial" (there could be special cases where it's not really initial) height.
   - on height change, the "above bottom" delegate would have to communicate the height offset to the list view
   - onDestruction, set offsets would have to be reset in the list view
   - the list view would have to somehow reposition itself (also changing height?) according to the total offset. I don't think contentY would work well.
   - after cooldown, list view could possibly reset the offset (delegates would have to listen for a signal there)

*) After writing all that: 
Perhaps a variation of 1 (keeping track of the bottom messages index as `currentIndex` & forcing `highlightRange` when a delegate's height was changed) could actually help with 2, after all.

Thoughts?

**Comment by Wunderfitz** [comment]
The first alternative was pretty much the solution I had before the initial release (well, without the bells and whistles, it only set `currentIndex` and `highlightFollowsCurrentItem`). It only took a while until the positioning was done (most certainly because the attributes which you mentioned were still default), but the positioning was always exact. So probably we should try that again with the changed attributes. :) 

The only drawback I noticed was that sometimes (I had no idea what caused that) the app crashed when I set currentIndex to the last element of the list. I validated that the index was valid, but it crashed anyway. So I ended up setting the index to the second last element of the index. ;) But well, before 0.1 I even removed that completely to change to the current solution.

**Comment by jgibbon** [comment]
I'm sad to say the PR does not completely fix this issue.
- In some cases, the position is still wrong. Because I've seen it with a huge amount of unread messages, I'd guess it happens when the number of unread messages exceed that of the initially loaded messages.
- The elusive last index crash does not appear to be fixed. I think this qualifies as a blocker for the next release. 
While I experienced it a few times last night, I haven't encountered it since removing the initial `chatView.currentIndex = -1;` – which most probably is just coincidence.

**Comment by Wunderfitz** [comment]
OK, the issues with the positioning in some cases should be checked. Hopefully, it can be reproduced...

The crash issue makes me sad on the one hand, on the other hand I'm pretty much relieved that I wasn't hallucinating when I did the testing before the initial release... @monich Any idea what could be the reason for that, does it ring any bell?

**Comment by jgibbon** [comment]
I've also noticed that currentIndex changes automatically, which doesn't account for all wrong positions (sometimes, ListView.ApplyRange doesn't seem to scroll, after all?) but for some. @monich mentioned that this happens when resetting the model (perhaps there's one too many [here](https://github.com/Wunderfitz/harbour-fernschreiber/blob/4049d4aa7cd3406ff137af6931b05faa2ddfe3cc/src/chatmodel.cpp#L273) which could possibly be handled with the "prepend else" further down?) – but I didn't find the actual reason in this case.

**Comment by jgibbon** [comment]
Even though it's part of this broad topic, as well, I've opened #136 last night, since it's pretty cleanly separable from the rest of this issue.

**Comment by jgibbon** [comment]
Perhaps the elusive crash has something to do with a new message arriving while the chatPage is initializing? 
I'm currently testing forwarding messages and without doing it inside a timer, it crashed every time.

**Comment by monich** [comment]
> Perhaps the elusive crash has something to do with a new message arriving while the chatPage is initializing?
> I'm currently testing forwarding messages and without doing it inside a timer, it crashed every time.

Great, reproducible crashes are easy to debug))

**Comment by Wunderfitz** [comment]
Positioning seems to work fine now, therefore closing this one for now. If issues come across, a new issue can be opened with the concrete error.
