### ISSUE TITLE
Outsource ChatPage messageListItem to external qml

### ISSUE THREAD

**Issue by jgibbon** [Wunderfitz/harbour-fernschreiber#95]
As it is, the ListItem does a lot of work while initializing and is a bit inflexible.
I propose to create something like a MessageListItemBase, which variants for different `content['@type']` can (not "must") inherit.

 - It would reduce the amount of Items/Loaders/Components/Properties and "ifs" needed while creating (new messages/scrolling) ListItems.
 - It would enable special message types to add their own context menu entries, which may reduce visual clutter on some upcoming types. (Yes I do have something in mind, but won't bother you with spoilers.)
 - It would enable display variants for messages. For example, "meta messages" like join/chat create/… could be much smaller and wouldn't even need most functionality of normal messages.
 - Perhaps it could also help to get rid of the delegateComponentLoadingTimer eventually, because that messes up scrolling upwards a bit – especially for Items with a large height. Not really sure, yet.

Obviously it would be a huge change and would take a while, but I would try it if you agree. And if the result is rubbish, we can discard it.

What are your thoughts?

cheers!

**Comment by Wunderfitz** [comment]
Well, I'm really open to improvements, so if you have something in mind, simply go ahead. I hope, history shows that I'm quite keen on merging things if they provide benefit. Furthermore, I'm really positively surprised that this project evolves into something bigger just because people like you contribute so much! :)

The only thing we need to take care of is that we don't run into conflicts - but for now, I keep on focusing on tweaking the chat info page a bit and some bugfixes, so that shouldn't be a blocker. Moreover, I'm still in the process of migrating everything to my new OS installation which is not fully completed yet - and that slows me down. No matter what, maybe we should think of a project board or something similar...?

All the best, Sebastian

**Comment by jgibbon** [comment]
We're now adressing most of those points a bit differently, so I'll close this. 

Using a project board would be a splendid idea, though.
